#!bash
#
# bash completion support for hub.
# Extends __git_list_all_commands with hub commands
# -------------------------------------------------------------

# Check that git tab completion is available
if declare -F _git > /dev/null; then
  # Duplicate and rename the 'list_all_commands' function
  eval "$(declare -f __git_list_all_commands | \
        sed 's/__git_list_all_commands/__git_list_all_commands_without_hub/')"

  # Replace the original 'list_all_commands' function with extra hub commands
  __git_list_all_commands() {
    echo "
    pull-request
    fork
    create
    browse
    compare
    "
    __git_list_all_commands_without_hub
  }
fi
