#!/usr/bin/env bash
set -e

STATUS=0

{ ruby --version
  if [ -n "$TRAVIS" ]; then
    script/cached-bundle install --deployment --jobs=3 --retry=3 --path bundle
  else
    bundle install --path bundle
  fi
  bundle binstub cucumber ronn --path bin
} || {
  echo "You need Ruby 1.9 or higher and Bundler to run hub tests" >&2
  STATUS=1
}

if [ $STATUS -eq 0 ]; then
  echo "Everything OK."
fi

exit $STATUS
