#!/usr/bin/env bash
# Usage: script/brew-publish <formula-name> <repo> <version>
set -euo pipefail

brew_name="${1?}"
repo="${2?}"
version="${3?}"
shift 3

url="https://github.com/${repo}/archive/${version}.tar.gz"

exec brew bump-formula-pr --no-audit --no-browse --url="$url" "$brew_name" \
  --message="https://github.com/${repo}/releases/tag/${version}" "$@"
