#!/usr/bin/env bash
# Usage: script/build [-o output] [test]
#
# Sets up GOPATH and compiles hub. With `test`, runs tests instead.

set -e

setup_gopath() {
  TMP_GOPATH="${TMPDIR:-/tmp}/go"
  TMP_SELF="${TMP_GOPATH}/src/github.com/github/hub"

  export GOPATH=${TMP_GOPATH}

  if [ ! -e "$TMP_SELF" ]; then
    mkdir -p "${TMP_SELF%/*}"
    ln -snf "$PWD" "$TMP_SELF"
  fi
}

find_source_files() {
  find . -maxdepth 2 -name '*.go' -not -name '*_test.go' "$@"
}

count_changed_files() {
  printf %d $(find_source_files -newer "$1" | wc -l)
}

up_to_date() {
  [ -e "$1" ] && [ "$(count_changed_files "$1")" -eq 0 ]
}

# always build with noupdate for now until Hub 2.0 is released
build_hub() {
  setup_gopath
  [ -n "$1" ] && (up_to_date "$1" || go build -tags "noupdate" -ldflags "-X github.com/github/hub/commands.Version `./script/version`" -o "$1")
}

test_hub() {
  setup_gopath
  go test ./...
}

case "$1" in
"" )
  build_hub hub
  ;;
-o )
  shift
  build_hub $1
  ;;
test )
  test_hub
  ;;
-h | --help )
  sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
  exit
  ;;
* )
  "$0" --help >&2
  exit 1
esac
