#!/usr/bin/env bash

# This script is only used by importing into other scripts.
GO_VERSION_REGEX="go(1\.[89]|[2-9]\.[0-9]{1,}|[0-9]{2,}\.[0-9]{1,})(\.[0-9]{1,})?[[:space:]]"

check_go_version() {
  if ! go version | grep -E $GO_VERSION_REGEX &> /dev/null; then
    echo "You need to install Go 1.8 or higher to build hub" >&2
    exit 1
  else
    go version
  fi
}

test_go_version() {
  if ! echo $1 | grep -E $GO_VERSION_REGEX &> /dev/null; then
    echo "FAIL $1" >&2
  else
    echo "PASS $1"
  fi
}

test_go_versions() {
  test_go_version "go version go0.1 darwin/amd64"
  test_go_version "go version go0.2 darwin/amd64"
  test_go_version "go version go1.6 darwin/amd64"
  test_go_version "go version go1.7.8 darwin/amd64"
  test_go_version "go version go1.8 darwin/amd64"
  test_go_version "go version go1.8.1 darwin/amd64"
  test_go_version "go version go1.8.10 darwin/amd64"
  test_go_version "go version go1.9 darwin/amd64"
  test_go_version "go version go2.0 darwin/amd64"
  test_go_version "go version go2.0.1 darwin/amd64"
  test_go_version "go version go3.1 darwin/amd64"
  test_go_version "go version go4.5 darwin/amd64"
  test_go_version "go version go5.6 darwin/amd64"
  test_go_version "go version go6.7 darwin/amd64"
  test_go_version "go version go10.1 darwin/amd64"
  test_go_version "go version go10.1 darwin/amd64"
  test_go_version "go version go10.10.10 darwin/amd64"
}
