#!/usr/bin/env bash
# Usage: script/build [test]
#
# Sets up GOPATH and run command

set -e

TMP_GOPATH="${TMPDIR:-/tmp}/go"
TMP_SELF="${TMP_GOPATH}/src/github.com/github/hub"

export GOPATH="${TMP_GOPATH}:${PWD}/Godeps/_workspace:$GOPATH"

if [ ! -e "$TMP_SELF" ]; then
  mkdir -p "${TMP_SELF%/*}"
  ln -snf "$PWD" "$TMP_SELF"
fi

$@
