#!/usr/bin/env bash
# Usage: script/package <tarball>
set -e

tarball_file="${1?}"
archive_path="${tarball_file%.tgz}"

rm -rf "$archive_path" "$tarball_file"
mkdir -p "$archive_path"

rsync -rR --exclude '*.md' --exclude '*.stamp' bin/hub README.md LICENSE etc share "$archive_path/"
cp script/install.sh "${archive_path}/install"
chmod +x "${archive_path}/install"

tar -czf "$tarball_file" -C "$(dirname "$archive_path")" -- "$(basename "$archive_path")"
rm -rf "$archive_path"
