#!/usr/bin/env bash
set -e

if [ -z "$GITHUB_ACTIONS" ] && tmux -V; then
  if [ -n "$CI" ]; then
    git --version
    bash --version | head -1
    zsh --version
    echo
  fi
  profile="all"
else
  echo "warning: skipping shell completion tests (install tmux to enable)" >&2
  profile="default"
fi

bin/cucumber -p "$profile" "$@"
