#!/usr/bin/env bash
# Displays hub's release version
version="$(git describe --tags HEAD 2>/dev/null)"

if [ -z "$version" ]; then
  version="$(grep Version commands/version.go | head -1 | cut -d '"' -f2)"
  sha="$(git rev-parse --short HEAD 2>/dev/null)"
  [ -z "$sha" ] || version="${version}-g${sha}"
fi

echo "${version#v}"
